<?php

namespace ContainerYN18711;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VD9M4p5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vD9M4p5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vD9M4p5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\CoverController::searchManga' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CoverController::searchManga()', 'getCoverControllersearchMangaService', true],
            'App\\Controller\\CoverController::ajaxSearchManga' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CoverController::ajaxSearchManga()', 'getCoverControllerajaxSearchMangaService', true],
            'App\\Controller\\CoverController::showScans' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CoverController::showScans()', 'getCoverControllershowScansService', true],
            'App\\Controller\\CoverController::voirAnime' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CoverController::voirAnime()', 'getCoverControllervoirAnimeService', true],
            'App\\Controller\\CoverController::serieAnime' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CoverController::serieAnime()', 'getCoverControllerserieAnimeService', true],
            'App\\Controller\\CoverController::voirFilm' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CoverController::voirFilm()', 'getCoverControllervoirFilmService', true],
            'App\\Controller\\ErrorController::showError' => ['privates', '.service_locator..QZb1Mm.App\\Controller\\ErrorController::showError()', 'getErrorControllershowErrorService', true],
            'App\\Controller\\FilmController::catalogue' => ['privates', '.service_locator.q5OPPft.App\\Controller\\FilmController::catalogue()', 'getFilmControllercatalogueService', true],
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\MangaController::catalogue' => ['privates', '.service_locator.q5OPPft.App\\Controller\\MangaController::catalogue()', 'getMangaControllercatalogueService', true],
            'App\\Controller\\ScanController::ajouterScan' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ScanController::ajouterScan()', 'getScanControllerajouterScanService', true],
            'App\\Controller\\ScanController::ajouterChapitre' => ['privates', '.service_locator.5RQ1Fq9.App\\Controller\\ScanController::ajouterChapitre()', 'getScanControllerajouterChapitreService', true],
            'App\\Controller\\SerieController::catalogue' => ['privates', '.service_locator.q5OPPft.App\\Controller\\SerieController::catalogue()', 'getSerieControllercatalogueService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\CoverController:searchManga' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CoverController::searchManga()', 'getCoverControllersearchMangaService', true],
            'App\\Controller\\CoverController:ajaxSearchManga' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CoverController::ajaxSearchManga()', 'getCoverControllerajaxSearchMangaService', true],
            'App\\Controller\\CoverController:showScans' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CoverController::showScans()', 'getCoverControllershowScansService', true],
            'App\\Controller\\CoverController:voirAnime' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CoverController::voirAnime()', 'getCoverControllervoirAnimeService', true],
            'App\\Controller\\CoverController:serieAnime' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CoverController::serieAnime()', 'getCoverControllerserieAnimeService', true],
            'App\\Controller\\CoverController:voirFilm' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CoverController::voirFilm()', 'getCoverControllervoirFilmService', true],
            'App\\Controller\\ErrorController:showError' => ['privates', '.service_locator..QZb1Mm.App\\Controller\\ErrorController::showError()', 'getErrorControllershowErrorService', true],
            'App\\Controller\\FilmController:catalogue' => ['privates', '.service_locator.q5OPPft.App\\Controller\\FilmController::catalogue()', 'getFilmControllercatalogueService', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\MangaController:catalogue' => ['privates', '.service_locator.q5OPPft.App\\Controller\\MangaController::catalogue()', 'getMangaControllercatalogueService', true],
            'App\\Controller\\ScanController:ajouterScan' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ScanController::ajouterScan()', 'getScanControllerajouterScanService', true],
            'App\\Controller\\ScanController:ajouterChapitre' => ['privates', '.service_locator.5RQ1Fq9.App\\Controller\\ScanController::ajouterChapitre()', 'getScanControllerajouterChapitreService', true],
            'App\\Controller\\SerieController:catalogue' => ['privates', '.service_locator.q5OPPft.App\\Controller\\SerieController::catalogue()', 'getSerieControllercatalogueService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CoverController::searchManga' => '?',
            'App\\Controller\\CoverController::ajaxSearchManga' => '?',
            'App\\Controller\\CoverController::showScans' => '?',
            'App\\Controller\\CoverController::voirAnime' => '?',
            'App\\Controller\\CoverController::serieAnime' => '?',
            'App\\Controller\\CoverController::voirFilm' => '?',
            'App\\Controller\\ErrorController::showError' => '?',
            'App\\Controller\\FilmController::catalogue' => '?',
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\MangaController::catalogue' => '?',
            'App\\Controller\\ScanController::ajouterScan' => '?',
            'App\\Controller\\ScanController::ajouterChapitre' => '?',
            'App\\Controller\\SerieController::catalogue' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CoverController:searchManga' => '?',
            'App\\Controller\\CoverController:ajaxSearchManga' => '?',
            'App\\Controller\\CoverController:showScans' => '?',
            'App\\Controller\\CoverController:voirAnime' => '?',
            'App\\Controller\\CoverController:serieAnime' => '?',
            'App\\Controller\\CoverController:voirFilm' => '?',
            'App\\Controller\\ErrorController:showError' => '?',
            'App\\Controller\\FilmController:catalogue' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\MangaController:catalogue' => '?',
            'App\\Controller\\ScanController:ajouterScan' => '?',
            'App\\Controller\\ScanController:ajouterChapitre' => '?',
            'App\\Controller\\SerieController:catalogue' => '?',
        ]);
    }
}
