<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV3xE2Ct\App_KernelEnvDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV3xE2Ct/App_KernelEnvDebugContainer.php') {
    touch(__DIR__.'/ContainerV3xE2Ct.legacy');

    return;
}

if (!\class_exists(App_KernelEnvDebugContainer::class, false)) {
    \class_alias(\ContainerV3xE2Ct\App_KernelEnvDebugContainer::class, App_KernelEnvDebugContainer::class, false);
}

return new \ContainerV3xE2Ct\App_KernelEnvDebugContainer([
    'container.build_hash' => 'V3xE2Ct',
    'container.build_id' => 'd23adc8e',
    'container.build_time' => 1727993911,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV3xE2Ct');
