<?php

namespace ContainerJPT58QF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\CoverController::searchManga' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CoverController::searchManga()', 'getCoverControllersearchMangaService', true],
            'App\\Controller\\CoverController::ajaxSearchManga' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CoverController::ajaxSearchManga()', 'getCoverControllerajaxSearchMangaService', true],
            'App\\Controller\\CoverController::showScans' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CoverController::showScans()', 'getCoverControllershowScansService', true],
            'App\\Controller\\CoverController::voirAnime' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CoverController::voirAnime()', 'getCoverControllervoirAnimeService', true],
            'App\\Controller\\ErrorController::showError' => ['privates', '.service_locator..QZb1Mm.App\\Controller\\ErrorController::showError()', 'getErrorControllershowErrorService', true],
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\MangaController::catalogue' => ['privates', '.service_locator.q5OPPft.App\\Controller\\MangaController::catalogue()', 'getMangaControllercatalogueService', true],
            'App\\Controller\\ScanController::ajouterScan' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ScanController::ajouterScan()', 'getScanControllerajouterScanService', true],
            'App\\Controller\\ScanController::ajouterChapitre' => ['privates', '.service_locator.5RQ1Fq9.App\\Controller\\ScanController::ajouterChapitre()', 'getScanControllerajouterChapitreService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\CoverController:searchManga' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CoverController::searchManga()', 'getCoverControllersearchMangaService', true],
            'App\\Controller\\CoverController:ajaxSearchManga' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CoverController::ajaxSearchManga()', 'getCoverControllerajaxSearchMangaService', true],
            'App\\Controller\\CoverController:showScans' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CoverController::showScans()', 'getCoverControllershowScansService', true],
            'App\\Controller\\CoverController:voirAnime' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CoverController::voirAnime()', 'getCoverControllervoirAnimeService', true],
            'App\\Controller\\ErrorController:showError' => ['privates', '.service_locator..QZb1Mm.App\\Controller\\ErrorController::showError()', 'getErrorControllershowErrorService', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\MangaController:catalogue' => ['privates', '.service_locator.q5OPPft.App\\Controller\\MangaController::catalogue()', 'getMangaControllercatalogueService', true],
            'App\\Controller\\ScanController:ajouterScan' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ScanController::ajouterScan()', 'getScanControllerajouterScanService', true],
            'App\\Controller\\ScanController:ajouterChapitre' => ['privates', '.service_locator.5RQ1Fq9.App\\Controller\\ScanController::ajouterChapitre()', 'getScanControllerajouterChapitreService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CoverController::searchManga' => '?',
            'App\\Controller\\CoverController::ajaxSearchManga' => '?',
            'App\\Controller\\CoverController::showScans' => '?',
            'App\\Controller\\CoverController::voirAnime' => '?',
            'App\\Controller\\ErrorController::showError' => '?',
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\MangaController::catalogue' => '?',
            'App\\Controller\\ScanController::ajouterScan' => '?',
            'App\\Controller\\ScanController::ajouterChapitre' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CoverController:searchManga' => '?',
            'App\\Controller\\CoverController:ajaxSearchManga' => '?',
            'App\\Controller\\CoverController:showScans' => '?',
            'App\\Controller\\CoverController:voirAnime' => '?',
            'App\\Controller\\ErrorController:showError' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\MangaController:catalogue' => '?',
            'App\\Controller\\ScanController:ajouterScan' => '?',
            'App\\Controller\\ScanController:ajouterChapitre' => '?',
        ]));
    }
}
