<?php

namespace ContainerJPT58QF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMangaControllercatalogueService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.q5OPPft.App\Controller\MangaController::catalogue()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q5OPPft.App\\Controller\\MangaController::catalogue()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cache' => ['services', 'cache.app', 'getCache_AppService', true],
        ], [
            'cache' => '?',
        ]))->withContext('App\\Controller\\MangaController::catalogue()', $container);
    }
}
