<?php

namespace ContainerJPT58QF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Logout_Listener_CookieClearing_MainService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.logout.listener.cookie_clearing.main' shared service.
     *
     * @return \Symfony\Component\Security\Http\EventListener\CookieClearingLogoutListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['security.logout.listener.cookie_clearing.main'] = new \Symfony\Component\Security\Http\EventListener\CookieClearingLogoutListener(['cookie_name' => ['path' => NULL, 'domain' => NULL, 'secure' => false, 'samesite' => NULL, 'partitioned' => false]]);
    }
}
