<?php

namespace ContainerJPT58QF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScanRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ScanRepository' shared autowired service.
     *
     * @return \App\Repository\ScanRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ScanRepository'] = new \App\Repository\ScanRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
