<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJPT58QF\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJPT58QF/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerJPT58QF.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerJPT58QF\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerJPT58QF\App_KernelProdContainer([
    'container.build_hash' => 'JPT58QF',
    'container.build_id' => '8417118e',
    'container.build_time' => 1729790455,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJPT58QF');
