<?php

namespace ContainerV3xE2Ct;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoverControllersearchMangaService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.P.blNFL.App\Controller\CoverController::searchManga()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.P.blNFL'] ?? $container->load('get_ServiceLocator_P_BlNFLService'));

        if (isset($container->privates['.service_locator.P.blNFL.App\\Controller\\CoverController::searchManga()'])) {
            return $container->privates['.service_locator.P.blNFL.App\\Controller\\CoverController::searchManga()'];
        }

        return $container->privates['.service_locator.P.blNFL.App\\Controller\\CoverController::searchManga()'] = $a->withContext('App\\Controller\\CoverController::searchManga()', $container);
    }
}
