<?php

namespace ContainerV3xE2Ct;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Logout_Listener_CookieClearing_MainService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private 'security.logout.listener.cookie_clearing.main' shared service.
     *
     * @return \Symfony\Component\Security\Http\EventListener\CookieClearingLogoutListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-http'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'CookieClearingLogoutListener.php';

        return $container->privates['security.logout.listener.cookie_clearing.main'] = new \Symfony\Component\Security\Http\EventListener\CookieClearingLogoutListener(['cookie_name' => ['path' => NULL, 'domain' => NULL, 'secure' => false, 'samesite' => NULL, 'partitioned' => false]]);
    }
}
