<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Anime extends \App\Entity\Anime implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'date_sortie' => [parent::class, 'date_sortie', null],
        "\0".parent::class."\0".'episode_number' => [parent::class, 'episode_number', null],
        "\0".parent::class."\0".'film' => [parent::class, 'film', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'lecteur_links' => [parent::class, 'lecteur_links', null],
        "\0".parent::class."\0".'manga_id' => [parent::class, 'manga_id', null],
        "\0".parent::class."\0".'saison_numero' => [parent::class, 'saison_numero', null],
        'date_sortie' => [parent::class, 'date_sortie', null],
        'episode_number' => [parent::class, 'episode_number', null],
        'film' => [parent::class, 'film', null],
        'id' => [parent::class, 'id', null],
        'lecteur_links' => [parent::class, 'lecteur_links', null],
        'manga_id' => [parent::class, 'manga_id', null],
        'saison_numero' => [parent::class, 'saison_numero', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
